[dataset]
lon_bounds = [270, 40]
lat_bounds = [20, 80]

[source_selection]
time_resolution_id = "6hrLev"
ssps = ["ssp585"]


[process]
scenario_path = "/work/ik1017/CMIP6/data/CMIP6/ScenarioMIP/MPI-M/MPI-ESM1-2-LR"
output_path = "/scratch/b/b382641/testdata"
overwrite_existing = false
dry_run = true 
